package igu;

public class AgendaPantalla extends javax.swing.JFrame {
    
        //tareas:
        /*Crear los vectores. Todos deben tener valor actual igual a null, para 
        que cuando << y >> los carguen a la primera, esten vacios (y reemplacen
        lo que esta escrito*/
                
        /*el boton >> tiene que avanzar por el indice de los vectores, del 0 al 9, 
        no avanzar mas que ahi. Cada vez que se lo pulsa, cambia el valor de textIndice 
        para mostrar en qué posicion del indice esta; y tiene que mostrar en los campos
        de texto los valores ingresados y guardados. Si no hay campos vacíos, tiene
        que mostrarlos vacios*/
        
        /*el boton << hace lo mismo que el otro. No tiene que ir por debajo de 0*/
        
        /*el boton Guardar hace que, si se ingresaron datos en los campos, esos datos 
        sean guardados en los vectores, y sigan apareciendo si se vuelve a ese indice
        con << y >>*/
    
        /*extras:
            -los botones << y >> se deshabilitan cuando llegan al tope
            -Los campos DNI y telefono solo admiten numeros
            -el DNI, telefono y fecha de nacimiento tienen un tope de caracteres
            -Fecha de nacimiento admite los formatos dd/mm/aaaa y dd-mm-aaaa*/
            
        String listaDNI[] = new String [10];    //los vectores que almacenan los datos. Los dejé como String porque no son afectados por calculos
        String listaNom[] = new String [10];    
        String listaApellido[] = new String [10];
        String listaDire[] = new String [10];
        String listaTel[] = new String [10];
        String listaFechaNac[] = new String[10];
        
        /*sabia que los vectores tenian que estar en algun lugar para ejecutarse
        antes que los botones, demore en encontrar dónde*/
        
        String indiceTxt = "0";     //el indice es string para tomar el dato de JtextField. Para ser usado lo parseo a int
               
    public AgendaPantalla() {
                
        initComponents();
               
               
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textDNI = new javax.swing.JTextField();
        textNombre = new javax.swing.JTextField();
        textApellido = new javax.swing.JTextField();
        textDireccion = new javax.swing.JTextField();
        textTelefono = new javax.swing.JTextField();
        textFechaNac = new javax.swing.JTextField();
        textIndice = new javax.swing.JTextField();
        btnGrabar = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textDNIKeyTyped(evt);
            }
        });

        textTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textTelefonoKeyTyped(evt);
            }
        });

        textFechaNac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFechaNacKeyTyped(evt);
            }
        });

        textIndice.setEditable(false);
        textIndice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textIndice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textIndice.setText("0");

        btnGrabar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnSiguiente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSiguiente.setText(">>");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnAnterior.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAnterior.setText("<<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Agenda electrónica");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("DNI:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Apellido:");

        jLabel5.setText("F. Nac:");

        jLabel6.setText("Telefono:");

        jLabel7.setText("Dirección:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Indice: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(19, 19, 19)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(textDNI)
                    .addComponent(textApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel5))
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textDireccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(textFechaNac)
                        .addComponent(textTelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(btnAnterior)
                        .addGap(18, 18, 18)
                        .addComponent(btnGrabar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSiguiente))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textIndice, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(28, 28, 28)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrabar)
                    .addComponent(btnSiguiente)
                    .addComponent(btnAnterior))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textIndice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        
        indiceTxt = textIndice.getText();
        int i = Integer.parseInt (indiceTxt); //toma el valor de indice y lo convierte en integral
        
        listaDNI[i] = textDNI.getText();    //usa el valor int como indice para invocar cada vector y grabar ahi lo ingresado
        listaNom[i] = textNombre.getText();
        listaApellido[i] = textApellido.getText();
        listaDire[i] = textDireccion.getText();
        listaTel[i] = textTelefono.getText();
        listaFechaNac[i]= textFechaNac.getText();
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        indiceTxt = textIndice.getText();
        int i = Integer.parseInt (indiceTxt);   //igual que en Grabar, convierte String en int
        
        if (i<9){
            i=i+1;                              //este if modifica el valor del cuadrito de indice, del 0 al 9
            indiceTxt = String.valueOf(i);      //convierte el int en String para ponerlo en el cuadro de texto
            textIndice.setText(indiceTxt);
            btnAnterior.setEnabled(true);       //esto hace que, si el boton << estaba deshabilitado, se habilite
        }
        
        if (i==9){
            btnSiguiente.setEnabled(false);     //esto hace que cuando llega a 9, el boton se pone gris y se deshabilita
        }
        
        //---------------
        
        textDNI.setText(listaDNI[i]);   //esto hace que, despues de modificar i, muestre lo que esta guardado en esa posicion
        textNombre.setText(listaNom[i]);
        textApellido.setText(listaApellido[i]);
        textDireccion.setText(listaDire[i]);
        textTelefono.setText(listaTel[i]);
        textFechaNac.setText(listaFechaNac[i]);
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        indiceTxt = textIndice.getText();
        int i = Integer.parseInt (indiceTxt);   //igual que en Grabar, convierte String en int
        
        if (i>0){
            i=i-1;                              //este if modifica el valor del cuadrito de indice, del 0 al 9
            indiceTxt = String.valueOf(i);      //convierte el int en String para ponerlo en el cuadro de texto
            textIndice.setText(indiceTxt);
            btnSiguiente.setEnabled(true);      //esto hace que si llego a 9 y despues bajo, el boton se habilite de nuevo
        }
        if (i==0){
            btnAnterior.setEnabled(false);     //esto hace que cuando llega a 0, el boton se pone gris y se deshabilita
        }
        //--------------
        
        textDNI.setText(listaDNI[i]);
        textNombre.setText(listaNom[i]);
        textApellido.setText(listaApellido[i]);
        textDireccion.setText(listaDire[i]);
        textTelefono.setText(listaTel[i]);
        textFechaNac.setText(listaFechaNac[i]);
        
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void textDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textDNIKeyTyped
        
        /*esto es para hacer que el campo numerico solo admita numeros*/
        
        char c = evt.getKeyChar();      //esto genera una variable c, que toma como valor la tecla que presiona el usuario
        if(!Character.isDigit(c)){      //esto verifica que el caracter c NO sea un digito
            evt.consume();              //en caso de que c no sea un digito, es consumido (el evento no es valido)
        }
        String largo = textDNI.getText();
        if(largo.length()==10){         //por cada tecla presionada, toma el contenido del campo de texto. Si tiene 10 caracteres, anula todo nuevo digito
            evt.consume(); 
        }
    }//GEN-LAST:event_textDNIKeyTyped

    private void textTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textTelefonoKeyTyped
        
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
        
        String largo = textTelefono.getText();
        if(largo.length()==8){      //el telefono tiene un tope de 8 caracteres
            evt.consume();
        }
    }//GEN-LAST:event_textTelefonoKeyTyped

    private void textFechaNacKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFechaNacKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c) && c != '/' && c != '-'){  //admite que se ingresen solo numeros, barra (/) o guion (-) para formar la fecha
            evt.consume();
        }
        
        String largo = textFechaNac.getText();
        if(largo.length()==10){      // admite el formato dd/mm/aaaa, despues borra todo caracter extra
            evt.consume();
        }
    }//GEN-LAST:event_textFechaNacKeyTyped

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField textApellido;
    private javax.swing.JTextField textDNI;
    private javax.swing.JTextField textDireccion;
    private javax.swing.JTextField textFechaNac;
    private javax.swing.JTextField textIndice;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textTelefono;
    // End of variables declaration//GEN-END:variables
}
